### ISSUE TITLE
Use perf_counter for performance measurement

### ISSUE THREAD

**Issue by presidento** [Dobatymo/genutility#4]
I suggest using `perf_counter` instead of `monotonic` for performance measurements in the [time.py](https://github.com/Dobatymo/genutility/blob/9452520f23ce5997ab34771681773cba0e9e8725/genutility/time.py) file, since for the very short items the resolution of `monotonic` may be not enough. But `perf_counter` uses "the highest available resolution to measure a short duration." (see [documentation](https://docs.python.org/3/library/time.html#time.perf_counter)).

**Comment by Dobatymo** [comment]
I read up a bit on clocks. I think it mostly makes a difference on windows. It seems at least for Windows <= 7 you may trade short term resolution with long term accuracy. There `perf_counter` can show drift on the order of a second per day (due to thermal drift of the quartz crystal)[0]. But on basically all other systems `perf_counter` should be the recommended way. So I will change it.

[0] <https://learn.microsoft.com/en-us/windows/win32/sysinfo/acquiring-high-resolution-time-stamps>

**Comment by Dobatymo** [comment]
Fixed https://github.com/Dobatymo/genutility/commit/b00bc9b29b31d244bfbcea83df1b8baff962ecc6
